const express = require('express');
const { getMyProfile, setUserAdmin, createUser, getAllMembers, triggerCalculatePendingAmounts } = require('../controllers/userController');
const { protect, isDeveloperPermission, isOwnerPermission } = require('../middleware/authMiddleware');
const { validateCreateUser } = require('../middleware/validationMiddleware');
const router = express.Router();
router.get('/', protect, getMyProfile);
// router.post('/setAdmin/:id', protect, isAdminPermission, setUserAdmin);
router.post('/create', protect, isOwnerPermission, validateCreateUser, createUser);
router.get('/members', protect, isOwnerPermission, getAllMembers);
router.post('/trigger-pending-calculation', protect, isDeveloperPermission, triggerCalculatePendingAmounts);
module.exports = router;